#!/bin/sh
# Compiles the C library to WebAssembly with Emscripten (emcc must be on the path) and writes it, as base64,
# to lib/src/wasm_bytes.dart, where the web implementation (lib/src/web.dart) reads it. That puts the
# WebAssembly inside the package's own Dart code, so there is no second file for an app to declare as an
# asset or to fetch. Run by scripts/vendor.sh, so a published package always carries it.
#
# The compiler flags and the list of exported functions are the same as in bindings/js/build.sh; keep the
# two in step. They are copied rather than shared so that neither package depends on the other.
#
# lib/src/wasm_bytes.dart is checked in only as an empty placeholder, so that the package analyses and builds
# for every platform without emcc. This script overwrites it: do not commit the result (git checkout
# lib/src/wasm_bytes.dart puts the placeholder back).
set -eu

here=$(cd "$(dirname "$0")/.." && pwd)
root=$(cd "$here/../.." && pwd)

command -v emcc >/dev/null 2>&1 || { echo "emcc not found: install Emscripten (https://emscripten.org) and put it on the path" >&2; exit 1; }
[ -f "$root/include/speechwarp.h" ] || { echo "No repository to build from at $root" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The functions of include/speechwarp.h, plus malloc and free for passing audio across.
exports=_malloc,_free
for name in $(grep -o 'speechwarp_[a-z0-9_]*(' "$root/include/speechwarp.h" | tr -d '(' | sort -u); do
  exports=$exports,_$name
done

# STANDALONE_WASM: no Emscripten JavaScript runtime, so the file needs nothing but WebAssembly.
# NDEBUG: upstream is full of assertions.
emcc -O3 -DNDEBUG -I"$root/include" -I"$root/third_party/kissfft" \
  "$root/src/speechwarp.c" "$root/src/trainer.c" "$root/src/fft.c" "$root/src/third_party_kissfft.c" \
  "$root/src/third_party_sonic.c" "$root/src/third_party_speedy.c" \
  -sSTANDALONE_WASM --no-entry -sALLOW_MEMORY_GROWTH -sEXPORTED_FUNCTIONS="$exports" \
  -o "$work/speechwarp.wasm"

# Not `base64 -w 0` (GNU only) or `base64 -i` (macOS only): tr works the same everywhere.
encoded=$(base64 < "$work/speechwarp.wasm" | tr -d '\n')
{
  echo "// Generated by scripts/build_web.sh. Do not edit, and do not commit this version of the file."
  echo "// ignore_for_file: lines_longer_than_80_chars"
  echo
  echo "/// The library compiled to WebAssembly, as base64."
  echo "const String wasmBase64 ="
  echo "    '$encoded';"
} > "$here/lib/src/wasm_bytes.dart"
echo "Wrote lib/src/wasm_bytes.dart ($(wc -c < "$work/speechwarp.wasm" | tr -d ' ') bytes of WebAssembly)"
