add_executable(example_player player.c)
set_target_properties(example_player PROPERTIES OUTPUT_NAME player C_STANDARD 99)
if(SPEECHWARP_BUILD_STATIC)
  target_link_libraries(example_player PRIVATE speechwarp_static)
else()
  target_link_libraries(example_player PRIVATE speechwarp_shared)
endif()
if(speechwarp_has_libm)
  target_link_libraries(example_player PRIVATE m)
endif()
if(SPEECHWARP_BUILD_TESTS)
  # Run as a test so that the example cannot rot.
  add_test(NAME example_player COMMAND example_player)
  set_tests_properties(example_player PROPERTIES PASS_REGULAR_EXPRESSION "finished at 60.00 s of 60.00 s")
endif()
