# Runs the command-line tool on WAV files from make_wav and checks the length of what it writes.
set(plain ${DIR}/tool_plain.wav)
set(extensible ${DIR}/tool_extensible.wav)
execute_process(COMMAND ${MAKE_WAV} ${plain} ${extensible} RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "make_wav failed")
endif()
file(SIZE ${plain} plain_size)
math(EXPR input_bytes "${plain_size} - 44")

function(run expected_divisor channels)
  execute_process(COMMAND ${TOOL} ${ARGN} ${DIR}/tool_out.wav RESULT_VARIABLE result ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "speechwarp ${ARGN} failed: ${error}")
  endif()
  file(SIZE ${DIR}/tool_out.wav size)
  math(EXPR expected "${input_bytes} * ${channels} * 100 / ${expected_divisor}")
  math(EXPR low "${expected} * 90 / 100")
  math(EXPR high "${expected} * 110 / 100")
  if(size LESS low OR size GREATER high)
    message(FATAL_ERROR "speechwarp ${ARGN}: wrote ${size} bytes, expected about ${expected}")
  endif()
  # The header must agree with the file.
  file(READ ${DIR}/tool_out.wav header OFFSET 40 LIMIT 4 HEX)
  string(REGEX REPLACE "(..)(..)(..)(..)" "\\4\\3\\2\\1" header "${header}")
  math(EXPR data_bytes "0x${header}")
  math(EXPR expected_data "${size} - 44")
  if(NOT data_bytes EQUAL expected_data)
    message(FATAL_ERROR "speechwarp ${ARGN}: header says ${data_bytes} data bytes, file has ${expected_data}")
  endif()
endfunction()

# The divisor is the speed times 100.
run(100 1 --speed 1 ${plain})
run(300 1 -s 3 ${plain})
run(300 1 --linear --speed 3 ${plain})
run(600 1 --nonlinear 0.5 --speed 6 ${plain})
run(300 2 --speed 3 ${extensible})

# Mistakes are reported, not crashed on.
foreach(arguments "--speed;0;${plain};${DIR}/tool_out.wav" "--bogus;${plain};${DIR}/tool_out.wav" "${plain}"
                  "${DIR}/missing.wav;${DIR}/tool_out.wav" "${CMAKE_CURRENT_LIST_FILE};${DIR}/tool_out.wav")
  execute_process(COMMAND ${TOOL} ${arguments} RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_QUIET)
  if(NOT result EQUAL 1 AND NOT result EQUAL 2)
    message(FATAL_ERROR "speechwarp ${arguments}: expected an error, got ${result}")
  endif()
  if(error STREQUAL "")
    message(FATAL_ERROR "speechwarp ${arguments}: failed without saying why")
  endif()
endforeach()
