# Checks the symbols a built library defines.
#   static: every external symbol starts with speechwarp_ (the third-party ones via src/rename.h).
#   shared: the exported symbols are exactly the functions declared in the public header.
if(KIND STREQUAL "shared")
  if(APPLE)
    set(flags -gU)
  else()
    set(flags -D --defined-only)
  endif()
else()
  set(flags -g --defined-only)
endif()

execute_process(COMMAND ${NM} ${flags} ${LIBRARY} OUTPUT_VARIABLE output RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "nm failed on ${LIBRARY}")
endif()

string(REGEX MATCHALL "[0-9a-fA-F]+ [A-Za-z] [^\n]+" lines "${output}")
set(found)
foreach(line ${lines})
  string(REGEX REPLACE "^[0-9a-fA-F]+ [A-Za-z] _?" "" name "${line}")
  string(REGEX REPLACE "@.*" "" name "${name}")  # ELF symbol versions
  # The linker adds these to every ELF shared library.
  if(NOT name MATCHES "^(_?init|_?fini|_?_bss_start|_?edata|_?end|_?_end__|_?_bss_end__|_?_bss_start__)$")
    list(APPEND found ${name})
  endif()
endforeach()
list(REMOVE_DUPLICATES found)
list(SORT found)

if(KIND STREQUAL "shared")
  file(READ ${HEADER} header)
  string(REGEX MATCHALL "speechwarp_[a-z0-9_]+\\(" declared "${header}")
  list(TRANSFORM declared REPLACE "\\($" "")
  list(REMOVE_DUPLICATES declared)
  list(SORT declared)
  if(NOT "${found}" STREQUAL "${declared}")
    message(FATAL_ERROR "Exported symbols differ from the header.\n exported: ${found}\n declared: ${declared}")
  endif()
else()
  foreach(name ${found})
    if(NOT name MATCHES "^speechwarp_")
      message(FATAL_ERROR "${name} is not prefixed. Add it to src/rename.h.")
    endif()
  endforeach()
endif()
list(LENGTH found count)
message(STATUS "${count} symbols checked in ${LIBRARY}")
