#!/bin/sh
# Builds dist/: the library compiled to WebAssembly with Emscripten (emcc must be on the path), embedded in
# a JavaScript module, and the TypeScript wrapper compiled beside it. Run `npm install` first.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
cd "$here"
mkdir -p build

# The functions of include/speechwarp.h, plus malloc and free for passing audio across.
exports=_malloc,_free
for name in $(grep -o 'speechwarp_[a-z0-9_]*(' "$root/include/speechwarp.h" | tr -d '(' | sort -u); do
  exports=$exports,_$name
done

# STANDALONE_WASM: no Emscripten JavaScript runtime, so the same file loads in a browser, in Node and in an
# AudioWorklet, where much of that runtime is unavailable. NDEBUG: upstream is full of assertions.
emcc -O3 -DNDEBUG -I"$root/include" -I"$root/third_party/kissfft" \
  "$root/src/speechwarp.c" "$root/src/fft.c" "$root/src/third_party_kissfft.c" \
  "$root/src/third_party_sonic.c" "$root/src/third_party_speedy.c" \
  -sSTANDALONE_WASM --no-entry -sALLOW_MEMORY_GROWTH -sEXPORTED_FUNCTIONS="$exports" \
  -o build/speechwarp.wasm

# The WebAssembly goes inside a module as text, so there is no second file to fetch or for a bundler to
# place. It is small.
node -e '
  const fs = require("fs");
  const base64 = fs.readFileSync("build/speechwarp.wasm").toString("base64");
  fs.writeFileSync("src/wasm.ts", "// Generated by build.sh.\nexport const wasmBase64: string =\n  \"" + base64 + "\";\n");
'

rm -rf dist
npx tsc
cp example/speechwarp-processor.js dist/

# The licences of what the WebAssembly contains must travel with the package.
rm -rf licenses
mkdir -p licenses/sonic licenses/speedy licenses/kissfft
cp "$root/LICENSE" "$root/NOTICE" licenses/
cp "$root/third_party/sonic/LICENSE" licenses/sonic/
cp "$root/third_party/speedy/LICENSE" licenses/speedy/
cp "$root/third_party/kissfft/COPYING" "$root/third_party/kissfft/LICENSES/BSD-3-Clause" licenses/kissfft/
