/* Gives every external symbol in the third-party sources a speechwarp_priv_ prefix.
 *
 * Sonic and KISS FFT are embedded in many programs (Android ships its own libsonic), so a static speechwarp
 * library would otherwise clash with them at link time. Each src/third_party_*.c includes this file and then
 * the upstream source, which leaves the files in third_party/ untouched.
 *
 * The list is every symbol `nm -g --defined-only` reports for those objects. tests/check_symbols.cmake fails
 * if an upstream update adds one that is missing here.
 */
#ifndef SPEECHWARP_RENAME_H_
#define SPEECHWARP_RENAME_H_

#define sonicGetChordPitch speechwarp_priv_sonicGetChordPitch
#define sonicIntChangeFloatSpeed speechwarp_priv_sonicIntChangeFloatSpeed
#define sonicIntChangeShortSpeed speechwarp_priv_sonicIntChangeShortSpeed
#define sonicIntCreateStream speechwarp_priv_sonicIntCreateStream
#define sonicIntDestroyStream speechwarp_priv_sonicIntDestroyStream
#define sonicIntFlushStream speechwarp_priv_sonicIntFlushStream
#define sonicIntGetNumChannels speechwarp_priv_sonicIntGetNumChannels
#define sonicIntGetPitch speechwarp_priv_sonicIntGetPitch
#define sonicIntGetQuality speechwarp_priv_sonicIntGetQuality
#define sonicIntGetRate speechwarp_priv_sonicIntGetRate
#define sonicIntGetSampleRate speechwarp_priv_sonicIntGetSampleRate
#define sonicIntGetSpeed speechwarp_priv_sonicIntGetSpeed
#define sonicIntGetUserData speechwarp_priv_sonicIntGetUserData
#define sonicIntGetVolume speechwarp_priv_sonicIntGetVolume
#define sonicIntReadFloatFromStream speechwarp_priv_sonicIntReadFloatFromStream
#define sonicIntReadShortFromStream speechwarp_priv_sonicIntReadShortFromStream
#define sonicIntReadUnsignedCharFromStream speechwarp_priv_sonicIntReadUnsignedCharFromStream
#define sonicIntSamplesAvailable speechwarp_priv_sonicIntSamplesAvailable
#define sonicIntSetNumChannels speechwarp_priv_sonicIntSetNumChannels
#define sonicIntSetPitch speechwarp_priv_sonicIntSetPitch
#define sonicIntSetQuality speechwarp_priv_sonicIntSetQuality
#define sonicIntSetRate speechwarp_priv_sonicIntSetRate
#define sonicIntSetSampleRate speechwarp_priv_sonicIntSetSampleRate
#define sonicIntSetSpeed speechwarp_priv_sonicIntSetSpeed
#define sonicIntSetUserData speechwarp_priv_sonicIntSetUserData
#define sonicIntSetVolume speechwarp_priv_sonicIntSetVolume
#define sonicIntWriteFloatToStream speechwarp_priv_sonicIntWriteFloatToStream
#define sonicIntWriteShortToStream speechwarp_priv_sonicIntWriteShortToStream
#define sonicIntWriteUnsignedCharToStream speechwarp_priv_sonicIntWriteUnsignedCharToStream
#define sonicSetChordPitch speechwarp_priv_sonicSetChordPitch

#define CreateFirstOrderFilter speechwarp_priv_CreateFirstOrderFilter
#define DeleteFirstOrderFilter speechwarp_priv_DeleteFirstOrderFilter
#define DesignFirstOrderLowpassFilter speechwarp_priv_DesignFirstOrderLowpassFilter
#define IterateFirstOrderFilter speechwarp_priv_IterateFirstOrderFilter
#define kiss_abs speechwarp_priv_kiss_abs
#define modulo speechwarp_priv_modulo
#define ResetFirstOrderFilter speechwarp_priv_ResetFirstOrderFilter
#define SetFirstOrderFilterState speechwarp_priv_SetFirstOrderFilterState
#define speedyAddData speechwarp_priv_speedyAddData
#define speedyAddDataShort speechwarp_priv_speedyAddDataShort
#define speedyAddToHysteresisBuffer speechwarp_priv_speedyAddToHysteresisBuffer
#define speedyBinToFreq speechwarp_priv_speedyBinToFreq
#define speedyComputeLocalEnergy speechwarp_priv_speedyComputeLocalEnergy
#define speedyComputeSpectralDifference speechwarp_priv_speedyComputeSpectralDifference
#define speedyComputeSpeedFromTension speechwarp_priv_speedyComputeSpeedFromTension
#define speedyComputeTension speechwarp_priv_speedyComputeTension
#define speedyCreateStream speechwarp_priv_speedyCreateStream
#define speedyDestroyStream speechwarp_priv_speedyDestroyStream
#define speedyEvaluateHysteresis speechwarp_priv_speedyEvaluateHysteresis
#define speedyFFTSize speechwarp_priv_speedyFFTSize
#define speedyFreqToBin speechwarp_priv_speedyFreqToBin
#define speedyGetCurrentTime speechwarp_priv_speedyGetCurrentTime
#define speedyGetEnergyCompressed speechwarp_priv_speedyGetEnergyCompressed
#define speedyGetInternalNormalizedSpectrogram speechwarp_priv_speedyGetInternalNormalizedSpectrogram
#define speedyGetInternalSpectrogram speechwarp_priv_speedyGetInternalSpectrogram
#define speedyGetInternalState speechwarp_priv_speedyGetInternalState
#define speedyGetNormalizedSpectrogram speechwarp_priv_speedyGetNormalizedSpectrogram
#define speedyGetSpectrogram speechwarp_priv_speedyGetSpectrogram
#define speedyGetSpectrogramAtTime speechwarp_priv_speedyGetSpectrogramAtTime
#define speedyGetSpeechChanges speechwarp_priv_speedyGetSpeechChanges
#define speedyInputFrameSize speechwarp_priv_speedyInputFrameSize
#define speedyInputFrameStep speechwarp_priv_speedyInputFrameStep
#define speedyNormalizeByEnergy speechwarp_priv_speedyNormalizeByEnergy
#define speedyPreemphasisFilter speechwarp_priv_speedyPreemphasisFilter
#define speedySaveSpectrogramData speechwarp_priv_speedySaveSpectrogramData
#define speedySpectrogram speechwarp_priv_speedySpectrogram

#define kiss_fft speechwarp_priv_kiss_fft
#define kiss_fft_alloc speechwarp_priv_kiss_fft_alloc
#define kiss_fft_cleanup speechwarp_priv_kiss_fft_cleanup
#define kiss_fft_next_fast_size speechwarp_priv_kiss_fft_next_fast_size
#define kiss_fft_stride speechwarp_priv_kiss_fft_stride

#endif  /* SPEECHWARP_RENAME_H_ */
